import 'core-js/modules/es6.object.create';
// import 'core-js/modules/es6.promise';
import 'core-js/modules/es6.array.is-array';
import 'core-js/modules/es6.array.index-of';
import 'core-js/modules/es6.array.filter';
import 'core-js/modules/es6.array.find';
import 'core-js/modules/es6.array.fill';
import 'core-js/modules/es6.array.map';
import 'core-js/modules/es6.array.some';
import 'core-js/modules/es6.function.bind';
import 'core-js/modules/es6.object.assign';
import 'core-js/modules/es6.string.trim';
import 'core-js/modules/es6.string.ends-with';
import 'core-js/modules/es6.date.to-iso-string';
import 'core-js/modules/es6.date.now';
import 'core-js/modules/es7.object.values';
import 'whatwg-fetch';
